/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MiPerfilRouteImport } from './routes/mi-perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminTramitesRouteImport } from './routes/admin/tramites'
import { Route as AdminReportesRouteImport } from './routes/admin/reportes'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminConfiguracionRouteImport } from './routes/admin/configuracion'
import { Route as AdminCitasRouteImport } from './routes/admin/citas'

const MiPerfilRoute = MiPerfilRouteImport.update({
  id: '/mi-perfil',
  path: '/mi-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTramitesRoute = AdminTramitesRouteImport.update({
  id: '/tramites',
  path: '/tramites',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCitasRoute = AdminCitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/mi-perfil': typeof MiPerfilRoute
  '/admin/citas': typeof AdminCitasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/tramites': typeof AdminTramitesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/mi-perfil': typeof MiPerfilRoute
  '/admin/citas': typeof AdminCitasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/tramites': typeof AdminTramitesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/mi-perfil': typeof MiPerfilRoute
  '/admin/citas': typeof AdminCitasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/tramites': typeof AdminTramitesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agendar'
    | '/login'
    | '/mi-perfil'
    | '/admin/citas'
    | '/admin/configuracion'
    | '/admin/login'
    | '/admin/reportes'
    | '/admin/tramites'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/login'
    | '/mi-perfil'
    | '/admin/citas'
    | '/admin/configuracion'
    | '/admin/login'
    | '/admin/reportes'
    | '/admin/tramites'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agendar'
    | '/login'
    | '/mi-perfil'
    | '/admin/citas'
    | '/admin/configuracion'
    | '/admin/login'
    | '/admin/reportes'
    | '/admin/tramites'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AgendarRoute: typeof AgendarRoute
  LoginRoute: typeof LoginRoute
  MiPerfilRoute: typeof MiPerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mi-perfil': {
      id: '/mi-perfil'
      path: '/mi-perfil'
      fullPath: '/mi-perfil'
      preLoaderRoute: typeof MiPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tramites': {
      id: '/admin/tramites'
      path: '/tramites'
      fullPath: '/admin/tramites'
      preLoaderRoute: typeof AdminTramitesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/citas': {
      id: '/admin/citas'
      path: '/citas'
      fullPath: '/admin/citas'
      preLoaderRoute: typeof AdminCitasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCitasRoute: typeof AdminCitasRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminTramitesRoute: typeof AdminTramitesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCitasRoute: AdminCitasRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminTramitesRoute: AdminTramitesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AgendarRoute: AgendarRoute,
  LoginRoute: LoginRoute,
  MiPerfilRoute: MiPerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
