#!/usr/bin/env python3
"""
Build PocketBase skill references from the PocketBase site repository.

This script extracts the rendered HTML generated by the Svelte site build and
groups the documentation into a handful of curated reference files that are
easy to consult from the skill.
"""

from __future__ import annotations

import argparse
import html
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path


GROUPS = {
    "core-concepts": [
        ("docs", "Introduction"),
        ("docs/how-to-use", "How to use PocketBase"),
        ("docs/collections", "Collections"),
        ("docs/api-rules-and-filters", "API rules and filters"),
        ("docs/authentication", "Authentication"),
        ("docs/files-handling", "Files upload and handling"),
        ("docs/working-with-relations", "Working with relations"),
        ("docs/use-as-framework", "Extending PocketBase"),
    ],
    "web-api": [
        ("docs/api-records", "API Records"),
        ("docs/api-realtime", "API Realtime"),
        ("docs/api-files", "API Files"),
        ("docs/api-collections", "API Collections"),
        ("docs/api-settings", "API Settings"),
        ("docs/api-logs", "API Logs"),
        ("docs/api-crons", "API Crons"),
        ("docs/api-backups", "API Backups"),
        ("docs/api-health", "API Health"),
    ],
    "go-framework": [
        ("docs/go-overview", "Overview"),
        ("docs/go-event-hooks", "Event hooks"),
        ("docs/go-routing", "Routing"),
        ("docs/go-database", "Database"),
        ("docs/go-records", "Record operations"),
        ("docs/go-collections", "Collection operations"),
        ("docs/go-migrations", "Migrations"),
        ("docs/go-jobs-scheduling", "Jobs scheduling"),
        ("docs/go-sending-emails", "Sending emails"),
        ("docs/go-rendering-templates", "Rendering templates"),
        ("docs/go-console-commands", "Console commands"),
        ("docs/go-realtime", "Realtime messaging"),
        ("docs/go-filesystem", "Filesystem"),
        ("docs/go-logging", "Logging"),
        ("docs/go-testing", "Testing"),
        ("docs/go-miscellaneous", "Miscellaneous"),
        ("docs/go-record-proxy", "Record proxy"),
    ],
    "javascript-framework": [
        ("docs/js-overview", "Overview"),
        ("docs/js-event-hooks", "Event hooks"),
        ("docs/js-routing", "Routing"),
        ("docs/js-database", "Database"),
        ("docs/js-records", "Record operations"),
        ("docs/js-collections", "Collection operations"),
        ("docs/js-migrations", "Migrations"),
        ("docs/js-jobs-scheduling", "Jobs scheduling"),
        ("docs/js-sending-emails", "Sending emails"),
        ("docs/js-rendering-templates", "Rendering templates"),
        ("docs/js-console-commands", "Console commands"),
        ("docs/js-sending-http-requests", "Sending HTTP requests"),
        ("docs/js-realtime", "Realtime messaging"),
        ("docs/js-filesystem", "Filesystem"),
        ("docs/js-logging", "Logging"),
    ],
    "operations-and-faq": [
        ("docs/going-to-production", "Going to production"),
        ("faq", "FAQ"),
    ],
    "upgrade-v023": [
        ("v023upgrade/go", "Upgrade to v0.23 - Go"),
        ("v023upgrade/jsvm", "Upgrade to v0.23 - JavaScript"),
    ],
}


MANIFEST_GROUP_ORDER = [
    "core-concepts",
    "web-api",
    "go-framework",
    "javascript-framework",
    "operations-and-faq",
    "upgrade-v023",
]


VOID_TAGS = {
    "area",
    "base",
    "br",
    "col",
    "embed",
    "hr",
    "img",
    "input",
    "link",
    "meta",
    "param",
    "source",
    "track",
    "wbr",
}


@dataclass
class PageDoc:
    route: str
    title: str
    source_html: Path
    source_svelte: str | None
    markdown: str


class ContentExtractor(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=False)
        self.capture_active = False
        self.capture_depth = 0
        self.skip_depth = 0
        self.parts: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr_map = {k: (v or "") for k, v in attrs}
        classes = set(attr_map.get("class", "").split())

        if not self.capture_active and tag == "div" and "data-pagefind-body" in attr_map:
            self.capture_active = True
            self.capture_depth = 1
            return

        if not self.capture_active:
            return

        if self.skip_depth > 0:
            if tag not in VOID_TAGS:
                self.skip_depth += 1
                self.capture_depth += 1
            return

        if (
            tag in {"script", "style"}
            or "docs-footer" in classes
            or "toc" in classes
            or ("hidden" in classes and "data-pagefind-meta" in attr_map)
        ):
            self.skip_depth = 1
            if tag not in VOID_TAGS:
                self.capture_depth += 1
            return

        self.parts.append(self.get_starttag_text())
        if tag not in VOID_TAGS:
            self.capture_depth += 1

    def handle_endtag(self, tag: str) -> None:
        if not self.capture_active:
            return

        if self.skip_depth > 0:
            self.skip_depth -= 1
            self.capture_depth -= 1
            if self.capture_depth == 0:
                self.capture_active = False
            return

        if self.capture_depth > 1:
            self.parts.append(f"</{tag}>")
        self.capture_depth -= 1
        if self.capture_depth == 0:
            self.capture_active = False

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if not self.capture_active or self.skip_depth > 0:
            return
        attr_text = "".join(
            f' {name}="{html.escape(value or "", quote=True)}"' for name, value in attrs
        )
        self.parts.append(f"<{tag}{attr_text} />")

    def handle_data(self, data: str) -> None:
        if self.capture_active and self.skip_depth == 0:
            self.parts.append(data)

    def handle_entityref(self, name: str) -> None:
        if self.capture_active and self.skip_depth == 0:
            self.parts.append(f"&{name};")

    def handle_charref(self, name: str) -> None:
        if self.capture_active and self.skip_depth == 0:
            self.parts.append(f"&#{name};")

    def render(self) -> str:
        return "".join(self.parts)


class FallbackContentExtractor(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=False)
        self.page_content_depth = 0
        self.capture_active = False
        self.capture_depth = 0
        self.parts: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr_map = {k: (v or "") for k, v in attrs}
        classes = set(attr_map.get("class", "").split())

        if not self.capture_active and self.page_content_depth == 0:
            if tag == "div" and "page-content" in classes:
                self.page_content_depth = 1
            return

        if self.page_content_depth > 0 and not self.capture_active:
            if tag == "div" and "content" in classes:
                self.capture_active = True
                self.capture_depth = 1
                return
            if tag not in VOID_TAGS:
                self.page_content_depth += 1
            return

        if not self.capture_active:
            return

        self.parts.append(self.get_starttag_text())
        if tag not in VOID_TAGS:
            self.capture_depth += 1

    def handle_endtag(self, tag: str) -> None:
        if self.capture_active:
            if self.capture_depth > 1:
                self.parts.append(f"</{tag}>")
            self.capture_depth -= 1
            if self.capture_depth == 0:
                self.capture_active = False
            return

        if self.page_content_depth > 0:
            self.page_content_depth -= 1

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if self.capture_active:
            attr_text = "".join(
                f' {name}="{html.escape(value or "", quote=True)}"' for name, value in attrs
            )
            self.parts.append(f"<{tag}{attr_text} />")

    def handle_data(self, data: str) -> None:
        if self.capture_active:
            self.parts.append(data)

    def handle_entityref(self, name: str) -> None:
        if self.capture_active:
            self.parts.append(f"&{name};")

    def handle_charref(self, name: str) -> None:
        if self.capture_active:
            self.parts.append(f"&#{name};")

    def render(self) -> str:
        return "".join(self.parts)


def run_command(command: list[str], cwd: Path) -> None:
    result = subprocess.run(command, cwd=str(cwd), check=False)
    if result.returncode != 0:
        raise RuntimeError(f"Command failed ({result.returncode}): {' '.join(command)}")


def maybe_build_site(site_root: Path) -> None:
    if not (site_root / "node_modules").exists():
        run_command(["npm", "install"], site_root)
    run_command(["npx", "vite", "build"], site_root)
    run_command(["npm", "run", "jstypes"], site_root)


def clean_code_snippet(text: str) -> str:
    text = re.sub(r"<!--\s*HTML_TAG_START\s*-->|<!--\s*HTML_TAG_END\s*-->", "", text)
    text = html.unescape(text)
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    lines = [line.rstrip() for line in text.splitlines()]

    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()

    if not lines:
        return ""

    indents = [
        len(re.match(r"^[ \t]*", line).group(0))
        for line in lines
        if line.strip()
    ]
    trim = min(indents) if indents else 0
    return "\n".join(line[trim:] for line in lines)


def strip_tags(text: str) -> str:
    text = re.sub(r"(?is)<(script|style)\b.*?</\1>", "", text)
    text = re.sub(r"(?i)<br\s*/?>", "\n", text)
    text = re.sub(r"(?is)</(p|div|section|article|blockquote|details|summary)>", "\n\n", text)
    text = re.sub(r"(?is)</li>", "\n", text)
    text = re.sub(r"(?is)<li\b[^>]*>", "- ", text)
    text = re.sub(r"(?is)</(ul|ol|table|thead|tbody|tr)>", "\n", text)
    text = re.sub(r"(?is)<(ul|ol|table|thead|tbody|tr)\b[^>]*>", "\n", text)
    text = re.sub(r"(?is)</t[dh]>", " | ", text)
    text = re.sub(r"(?is)<t[dh]\b[^>]*>", "", text)
    text = re.sub(r"(?is)<[^>]+>", "", text)
    text = html.unescape(text)
    text = text.replace("\xa0", " ")
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def convert_table(table_html: str) -> str:
    rows = re.findall(r"(?is)<tr\b[^>]*>(.*?)</tr>", table_html)
    parsed_rows: list[list[str]] = []

    for row_html in rows:
        cells = re.findall(r"(?is)<t[dh]\b[^>]*>(.*?)</t[dh]>", row_html)
        cleaned = [normalize_inline_text(strip_tags(cell)) for cell in cells]
        if any(cleaned):
            parsed_rows.append(cleaned)

    if not parsed_rows:
        return ""

    if len(parsed_rows) == 1:
        return "\n".join(f"- {cell}" for cell in parsed_rows[0] if cell)

    width = max(len(row) for row in parsed_rows)
    for row in parsed_rows:
        if len(row) < width:
            row.extend([""] * (width - len(row)))

    header = parsed_rows[0]
    separator = ["---"] * width
    table_lines = [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join(separator) + " |",
    ]
    for row in parsed_rows[1:]:
        table_lines.append("| " + " | ".join(row) + " |")
    return "\n".join(table_lines)


def normalize_inline_text(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def collapse_blank_lines(text: str) -> str:
    lines = [line.rstrip() for line in text.splitlines()]
    result: list[str] = []
    blank = False
    for line in lines:
        if line.strip():
            result.append(line)
            blank = False
        else:
            if not blank and result:
                result.append("")
            blank = True
    return "\n".join(result).strip() + "\n"


def html_to_markdown(content_html: str) -> str:
    text = content_html

    def repl_code(match: re.Match[str]) -> str:
        code_text = clean_code_snippet(strip_tags(match.group(1)))
        if not code_text:
            return "\n"
        return f"\n\n```\n{code_text}\n```\n\n"

    def repl_heading(match: re.Match[str]) -> str:
        level = min(int(match.group(1)), 6)
        title = normalize_inline_text(strip_tags(match.group(2)))
        return f"\n\n{'#' * level} {title}\n\n" if title else "\n"

    def repl_accordion(match: re.Match[str]) -> str:
        title = normalize_inline_text(strip_tags(match.group(1)))
        return f"\n\n### {title}\n\n" if title else "\n"

    def repl_table(match: re.Match[str]) -> str:
        table = convert_table(match.group(0))
        return f"\n\n{table}\n\n" if table else "\n"

    text = re.sub(
        r"(?is)<div\b[^>]*class=\"[^\"]*code-wrapper[^\"]*\"[^>]*>.*?<code\b[^>]*>(.*?)</code>.*?</div>",
        repl_code,
        text,
    )
    text = re.sub(
        r"(?is)<button\b[^>]*class=\"[^\"]*accordion-header[^\"]*\"[^>]*>.*?<a\b[^>]*>(.*?)</a>.*?</button>",
        repl_accordion,
        text,
    )
    text = re.sub(r"(?is)<h([1-6])\b[^>]*>(.*?)</h\1>", repl_heading, text)
    text = re.sub(r"(?is)<table\b[^>]*>.*?</table>", repl_table, text)
    text = strip_tags(text)
    text = re.sub(r"\n[ \t]*- ", "\n- ", text)
    text = re.sub(r"(?m)^[ \t]*\|\s*$", "", text)
    return collapse_blank_lines(text)


def route_to_html_path(site_root: Path, route: str) -> Path:
    return site_root / "build" / route / "index.html"


def route_to_svelte_path(route: str) -> str | None:
    if route == "faq":
        return "src/routes/(app)/faq/+page.svelte"
    if route.startswith("v023upgrade/"):
        tail = route[len("v023upgrade/") :]
        return f"src/routes/(app)/v023upgrade/{tail}/+page.svelte"
    if route == "docs":
        return "src/routes/(app)/docs/+page.svelte"
    if route.startswith("docs/"):
        tail = route[len("docs/") :]
        return f"src/routes/(app)/docs/{tail}/+page.svelte"
    return None


def parse_page(route: str, title: str, html_path: Path) -> PageDoc:
    raw_html = html_path.read_text(encoding="utf-8")
    extractor = ContentExtractor()
    extractor.feed(raw_html)
    content_html = extractor.render()
    if not content_html.strip():
        fallback = FallbackContentExtractor()
        fallback.feed(raw_html)
        content_html = fallback.render()
    markdown = html_to_markdown(content_html)
    return PageDoc(
        route=route,
        title=title,
        source_html=html_path,
        source_svelte=route_to_svelte_path(route),
        markdown=markdown,
    )


def read_version(site_root: Path) -> str:
    env_path = site_root / ".env"
    if not env_path.exists():
        return "unknown"
    match = re.search(r'(?m)^PB_VERSION\s*=\s*"([^"]+)"', env_path.read_text(encoding="utf-8"))
    return match.group(1) if match else "unknown"


def build_group_reference(
    group_name: str,
    docs: list[PageDoc],
    version: str,
    generated_at: str,
) -> str:
    title = {
        "core-concepts": "PocketBase Core Concepts",
        "web-api": "PocketBase Web API",
        "go-framework": "PocketBase Go Framework",
        "javascript-framework": "PocketBase JavaScript / JSVM",
        "operations-and-faq": "PocketBase Operations and FAQ",
        "upgrade-v023": "PocketBase Upgrade Guide (v0.23)",
    }[group_name]

    intro = {
        "core-concepts": "Rendered and extracted from the PocketBase site documentation pages that explain the platform fundamentals.",
        "web-api": "Rendered and extracted from the PocketBase Web APIs reference pages.",
        "go-framework": "Rendered and extracted from the PocketBase Go extension guides.",
        "javascript-framework": "Rendered and extracted from the PocketBase JavaScript / JSVM guides.",
        "operations-and-faq": "Rendered and extracted from the production and FAQ pages.",
        "upgrade-v023": "Rendered and extracted from the legacy v0.23 upgrade pages. Consult this only for older codebases and migrations.",
    }[group_name]

    lines = [
        f"# {title}",
        "",
        intro,
        "",
        f"- PocketBase version in source repo: `{version}`",
        f"- Generated from site repo: `{generated_at}`",
        "",
        "## Included pages",
        "",
    ]

    for doc in docs:
        source_svelte = doc.source_svelte or "n/a"
        lines.append(f"- `{doc.route}` -> `{source_svelte}`")

    lines.append("")

    for doc in docs:
        lines.append(f"## {doc.title}")
        lines.append("")
        lines.append(f"- Route: `/{doc.route}`")
        if doc.source_svelte:
            lines.append(f"- Source Svelte: `{doc.source_svelte}`")
        lines.append("")
        lines.append(doc.markdown.strip())
        lines.append("")

    return "\n".join(lines).strip() + "\n"


def build_manifest(
    grouped_docs: dict[str, list[PageDoc]],
    version: str,
    site_root: Path,
    generated_at: str,
) -> str:
    total_pages = sum(len(docs) for docs in grouped_docs.values())
    lines = [
        "# PocketBase Source Manifest",
        "",
        "- Skill source: PocketBase site repo",
        f"- Site root: `{site_root}`",
        f"- PocketBase version: `{version}`",
        f"- Generated at: `{generated_at}`",
        f"- Total extracted pages: `{total_pages}`",
        "",
        "## Reference files",
        "",
        "- `core-concepts.md`",
        "- `web-api.md`",
        "- `go-framework.md`",
        "- `javascript-framework.md`",
        "- `operations-and-faq.md`",
        "- `upgrade-v023.md`",
        "- `jsvm-api-index.md`",
        "- `jsvm-types.d.ts`",
        "",
        "## Route map",
        "",
    ]

    for group_name in MANIFEST_GROUP_ORDER:
        lines.append(f"### {group_name}")
        lines.append("")
        for doc in grouped_docs[group_name]:
            lines.append(
                f"- `/{doc.route}` -> `{doc.source_svelte or 'n/a'}` -> `{doc.source_html}`"
            )
        lines.append("")

    return "\n".join(lines).strip() + "\n"


def build_jsvm_index(types_path: Path, version: str, generated_at: str) -> str:
    lines = types_path.read_text(encoding="utf-8").splitlines()

    sections = {
        "Global variables": [],
        "Global functions": [],
        "Namespaces": [],
        "Classes": [],
        "Interfaces": [],
        "Type aliases": [],
    }

    patterns = [
        ("Global variables", re.compile(r"^\s*declare\s+var\s+([A-Za-z0-9_$]+)\b")),
        ("Global functions", re.compile(r"^\s*declare\s+function\s+([A-Za-z0-9_$]+)\b")),
        ("Namespaces", re.compile(r"^\s*(?:declare\s+)?namespace\s+([A-Za-z0-9_$]+)\b")),
        ("Classes", re.compile(r"^\s*(?:declare\s+)?class\s+([A-Za-z0-9_$]+)\b")),
        ("Interfaces", re.compile(r"^\s*(?:declare\s+)?interface\s+([A-Za-z0-9_$]+)\b")),
        ("Type aliases", re.compile(r"^\s*type\s+([A-Za-z0-9_$]+)\b")),
    ]

    for idx, line in enumerate(lines, start=1):
        for section, pattern in patterns:
            match = pattern.search(line)
            if match:
                sections[section].append((match.group(1), idx))
                break

    content = [
        "# PocketBase JSVM API Index",
        "",
        "This index is derived from `jsvm/types.d.ts` in the PocketBase site repo.",
        "",
        f"- PocketBase version in source repo: `{version}`",
        f"- Generated from site repo: `{generated_at}`",
        f"- Source file: `{types_path}`",
        "",
        "Use this file to quickly locate globally exposed JSVM symbols. For exact signatures, overloads, and comments, consult `jsvm-types.d.ts`.",
        "",
    ]

    for section, entries in sections.items():
        content.append(f"## {section}")
        content.append("")
        if not entries:
            content.append("- None found")
        else:
            for name, line_number in entries:
                content.append(f"- `{name}` (line {line_number})")
        content.append("")

    return "\n".join(content).strip() + "\n"


def write_file(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build PocketBase skill references.")
    parser.add_argument(
        "--site-root",
        default=".",
        help="Path to the PocketBase site repository root.",
    )
    parser.add_argument(
        "--references-dir",
        default=str(Path(__file__).resolve().parents[1] / "references"),
        help="Output directory for the generated reference files.",
    )
    parser.add_argument(
        "--build",
        action="store_true",
        help="Run npm install (if needed), vite build, and typedoc before extraction.",
    )
    args = parser.parse_args()

    site_root = Path(args.site_root).resolve()
    references_dir = Path(args.references_dir).resolve()

    if args.build:
        maybe_build_site(site_root)

    required_paths = [
        site_root / "build" / "docs",
        site_root / "build" / "faq" / "index.html",
        site_root / "build" / "v023upgrade" / "go" / "index.html",
        site_root / "build" / "v023upgrade" / "jsvm" / "index.html",
        site_root / "jsvm" / "types.d.ts",
    ]
    missing = [str(path) for path in required_paths if not path.exists()]
    if missing:
        print("Missing required build artifacts:", file=sys.stderr)
        for path in missing:
            print(f"- {path}", file=sys.stderr)
        print("Run with --build or generate the site build and JSVM docs first.", file=sys.stderr)
        return 1

    references_dir.mkdir(parents=True, exist_ok=True)

    version = read_version(site_root)
    generated_at = datetime.now(timezone.utc).isoformat()

    grouped_docs: dict[str, list[PageDoc]] = {}
    for group_name, routes in GROUPS.items():
        grouped_docs[group_name] = []
        for route, title in routes:
            html_path = route_to_html_path(site_root, route)
            grouped_docs[group_name].append(parse_page(route, title, html_path))

    write_file(
        references_dir / "core-concepts.md",
        build_group_reference("core-concepts", grouped_docs["core-concepts"], version, generated_at),
    )
    write_file(
        references_dir / "web-api.md",
        build_group_reference("web-api", grouped_docs["web-api"], version, generated_at),
    )
    write_file(
        references_dir / "go-framework.md",
        build_group_reference("go-framework", grouped_docs["go-framework"], version, generated_at),
    )
    write_file(
        references_dir / "javascript-framework.md",
        build_group_reference(
            "javascript-framework",
            grouped_docs["javascript-framework"],
            version,
            generated_at,
        ),
    )
    write_file(
        references_dir / "operations-and-faq.md",
        build_group_reference(
            "operations-and-faq",
            grouped_docs["operations-and-faq"],
            version,
            generated_at,
        ),
    )
    write_file(
        references_dir / "upgrade-v023.md",
        build_group_reference("upgrade-v023", grouped_docs["upgrade-v023"], version, generated_at),
    )
    write_file(
        references_dir / "source-manifest.md",
        build_manifest(grouped_docs, version, site_root, generated_at),
    )

    types_source = site_root / "jsvm" / "types.d.ts"
    write_file(
        references_dir / "jsvm-api-index.md",
        build_jsvm_index(types_source, version, generated_at),
    )
    shutil.copyfile(types_source, references_dir / "jsvm-types.d.ts")

    print(f"Generated PocketBase references in {references_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
